"""
RepoPilot Agent Core implementation (Person 1 Stage 4).
Executes a model-driven loop over repository tools and vector retrieval to answer user queries.
"""

import json
from typing import Any, Dict, List, Optional, Union

from backend.config import ConfigurationError
from backend.gemma import GemmaClient, GemmaAPIError
from backend.repository.models import Repository
from .context import InvestigationContext
from .models import AgentResponse, AgentState, AgentStep, ToolCall, ToolResult
from .prompts import SYSTEM_PROMPT
from .registry import ToolRegistry


class RepoPilotAgent:
    """
    Model-driven repository investigation agent powered by Gemma 4 and Stage 4 RAG retrieval.
    """

    def __init__(
        self,
        registry: ToolRegistry,
        gemma_client: Optional[GemmaClient] = None,
        max_iterations: int = 8,
        verbose: bool = False,
        enable_skills: bool = False,
    ):
        self._registry = registry
        self._gemma_client = gemma_client
        self._max_iterations = max_iterations
        self._verbose = verbose

        if enable_skills:
            self._registry.register_built_in_skills()

    @property
    def registry(self) -> ToolRegistry:
        """Returns the attached ToolRegistry."""
        return self._registry

    def _get_gemma_client(self) -> GemmaClient:
        """Returns or initializes the GemmaClient."""
        if self._gemma_client is None:
            self._gemma_client = GemmaClient()
        return self._gemma_client

    def run(self, question: str) -> AgentResponse:
        """
        Executes the agent investigation loop to answer a user question.

        Args:
            question: The user's question about the repository.

        Returns:
            AgentResponse: Final grounded answer with evidence citations and execution metadata.
        """
        if not question or not isinstance(question, str) or not question.strip():
            return AgentResponse(
                question=str(question),
                final_answer="Invalid question: Question must be a non-empty string.",
                evidence=[],
                steps_count=0,
                status="error",
                error="Empty question provided.",
            )

        state = AgentState(
            question=question.strip(),
            max_iterations=self._max_iterations,
            status="in_progress",
        )
        context = InvestigationContext()

        model_tools = self._registry.get_model_tools()

        # Build initial conversation history
        conversation_history: List[Dict[str, Any]] = [
            {"role": "user", "content": question.strip()}
        ]

        try:
            client = self._get_gemma_client()
        except (ConfigurationError, GemmaAPIError) as e:
            state.status = "error"
            state.error = str(e)
            return AgentResponse(
                question=state.question,
                final_answer=f"Agent initialization error: {e}",
                evidence=[],
                steps_count=0,
                status="error",
                error=str(e),
            )

        while state.iteration_count < state.max_iterations:
            state.iteration_count += 1
            step_num = state.iteration_count

            # Request model response
            try:
                response_dict = client.generate_with_tools(
                    contents=conversation_history,
                    tools=model_tools,
                    system_instruction=SYSTEM_PROMPT,
                )
            except (GemmaAPIError, Exception) as e:
                state.status = "error"
                state.error = str(e)
                err_msg = f"Model API error during step {step_num}: {e}"
                if state.evidence:
                    final_text = f"{err_msg}\n\nPartial evidence gathered from: {', '.join(state.evidence)}"
                else:
                    final_text = err_msg

                return AgentResponse(
                    question=state.question,
                    final_answer=final_text,
                    evidence=state.evidence,
                    steps_count=step_num,
                    status="error",
                    error=str(e),
                )

            thought_text = response_dict.get("text", "")
            raw_function_calls = response_dict.get("function_calls", [])

            step = AgentStep(step_number=step_num, thought=thought_text)

            if self._verbose:
                print(f"\n[Step {step_num}] Model text: {thought_text}")

            # If model issued no function calls, treat text as final answer
            if not raw_function_calls:
                state.final_answer = thought_text if thought_text else "No answer generated by model."
                state.status = "completed"
                state.steps.append(step)
                break

            # Process function calls
            step_tool_calls: List[ToolCall] = []
            step_tool_results: List[ToolResult] = []

            for raw_call in raw_function_calls:
                tool_name = raw_call.get("name", "")
                tool_args = raw_call.get("args", {})

                tool_call = ToolCall(name=tool_name, args=tool_args)
                step_tool_calls.append(tool_call)

                if self._verbose:
                    print(f"[Step {step_num}] Executing tool '{tool_name}' with args {tool_args}")

                # Execute via ToolRegistry (handles validation, security, context injection, and skills)
                tool_result = self._registry.execute(tool_name, tool_args, context=context)
                step_tool_results.append(tool_result)

                # Record evidence into state and context
                self._record_evidence(state, context, tool_name, tool_args, tool_result)

            step.tool_calls = step_tool_calls
            step.tool_results = step_tool_results
            state.steps.append(step)

            # Record turn in conversation history for next model iteration
            conversation_history.append({
                "role": "model",
                "content": thought_text,
                "function_calls": raw_function_calls,
            })

            # Format tool results for model feedback
            formatted_results = [tr.to_dict() for tr in step_tool_results]
            conversation_history.append({
                "role": "user",
                "content": f"Tool Results: {json.dumps(formatted_results)}",
                "function_results": formatted_results,
            })

        # Check if max iterations reached without explicit completion
        if state.status == "in_progress":
            state.status = "max_iterations_reached"
            summary_msg = f"Reached maximum iteration limit ({self._max_iterations} steps)."
            if state.evidence:
                state.final_answer = f"{summary_msg} Evidence gathered from: {', '.join(state.evidence)}."
            else:
                state.final_answer = f"{summary_msg} Unable to complete investigation within step limit."

        return AgentResponse(
            question=state.question,
            final_answer=state.final_answer or "No final answer produced.",
            evidence=list(dict.fromkeys(state.evidence)),
            steps_count=state.iteration_count,
            status=state.status,
            error=state.error,
        )

    def _record_evidence(
        self,
        state: AgentState,
        context: InvestigationContext,
        tool_name: str,
        tool_args: Dict[str, Any],
        tool_result: ToolResult,
    ) -> None:
        """Records evidence items and updates state citations."""
        if not tool_result.success:
            return

        res = tool_result.result
        if not isinstance(res, dict):
            return

        # Handle skill result evidence payload
        if "skill_name" in res and "evidence" in res:
            for loc in res.get("evidence", []):
                if loc and loc not in state.evidence:
                    state.evidence.append(loc)

        if tool_name == "search_repository":
            chunks = res.get("chunks", [])
            for c in chunks:
                path = c.get("path")
                start = c.get("start_line", 1)
                end = c.get("end_line", 1)
                snippet = c.get("content", "")
                score = c.get("score", 0.0)

                context.add_retrieved_chunk(path, start, end, snippet, score)
                chunk_loc = f"{path}:{start}-{end}"
                if chunk_loc not in state.evidence:
                    state.evidence.append(chunk_loc)

        elif tool_name == "read_file":
            path = res.get("path")
            content = res.get("content", "")
            if path:
                context.add_inspected_file(path, content[:200])
                if path not in state.evidence:
                    state.evidence.append(path)

        elif tool_name == "search_code":
            matches = res.get("matches", [])
            for m in matches:
                p = m.get("path")
                line = m.get("line", 1)
                snippet = m.get("snippet", "")
                if p:
                    context.add_search_match(p, line, snippet)
                    loc = f"{p}:{line}"
                    if loc not in state.evidence:
                        state.evidence.append(loc)

        elif tool_name == "list_files":
            files = res.get("files", [])
            for f in files[:5]:
                if f not in state.evidence:
                    state.evidence.append(f)
